default: &default
  adapter: mysql2
  encoding: utf8
  database: openshift_rails
  username: root
  password: testing
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: openshift_rails
  username: root
  password: testing
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  database: openshift_rails
  username: root
  password: testing
  host: localhost
  pool: 5
  timeout: 5000
